const $=s=>document.querySelector(s);let all=[],accepted=[],urls=[];const canvas=$('#canvas'),ctx=canvas.getContext('2d');
const natural=(a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'});const isCustom=f=>/\(custom\)/i.test(f.name);const base=n=>n.replace(/\s*\(custom\)/i,'').replace(/\.[^.]+$/,'').toLowerCase();
$('#pick').onclick=()=>$('#folder').click();$('#folder').onchange=e=>scan([...e.target.files]);$('#customOnly').onchange=filter;$('#order').onchange=filter;
function scan(files){all=files.filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));$('#scanned').textContent=all.length;filter();$('#workspace').hidden=false;$('#pickTitle').textContent=(files[0]?.webkitRelativePath.split('/')[0]||'Folder selected');}
function filter(){urls.forEach(URL.revokeObjectURL);urls=[];const customs=all.filter(isCustom), customBases=new Set(customs.map(f=>base(f.name)));const unmatched=all.filter(f=>!isCustom(f)&&!customBases.has(base(f.name)));accepted=$('#customOnly').checked?customs:[...customs,...unmatched];const order=$('#order').value;if(order==='filename')accepted.sort(natural);else if(order==='modified')accepted.sort((a,b)=>a.lastModified-b.lastModified||natural(a,b));else accepted.sort(()=>Math.random()-.5);$('#accepted').textContent=accepted.length;$('#ignored').textContent=all.length-accepted.length;$('#warnings').textContent=unmatched.length;$('#notice').textContent=`${customs.length} Custom copies found. ${unmatched.length} originals have no matching Custom copy.`;$('#countLabel').textContent=`Showing ${Math.min(accepted.length,100)} of ${accepted.length}`;showThumbs();}
function showThumbs(){const box=$('#thumbs');box.innerHTML='';accepted.slice(0,100).forEach(f=>{const u=URL.createObjectURL(f);urls.push(u);const im=new Image();im.src=u;im.title=f.name;box.append(im)});}
const load=f=>new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=URL.createObjectURL(f)});
function cover(img,x,y,w,h,zoom=1){const s=Math.max(w/img.width,h/img.height)*zoom,nw=img.width*s,nh=img.height*s;ctx.drawImage(img,x+(w-nw)/2,y+(h-nh)/2,nw,nh)}
function bg(t){const g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#132949');g.addColorStop(1,'#071327');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.globalAlpha=.25;ctx.strokeStyle='#31859d';for(let i=0;i<10;i++){ctx.beginPath();ctx.moveTo((i*143+t*100)%1200-100,i*139);ctx.lineTo((i*143+t*100)%1200+240,i*139+70);ctx.stroke()}ctx.globalAlpha=1}
function rounded(x,y,w,h,r=24){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.clip()}
function photo(img,x,y,w,h,t,delay=0,rot=0){const p=Math.max(0,Math.min(1,(t-delay)*3));ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(rot);ctx.scale(.88+.12*p,.88+.12*p);ctx.translate(-w/2,-h/2);rounded(0,0,w,h);cover(img,0,0,w,h,1.1-.05*p);ctx.restore()}
function frame(images,sceneT,index){bg(sceneT);ctx.fillStyle='white';ctx.font='700 37px Barlow';ctx.fillText('CXO',58,68);ctx.font='300 37px Barlow';ctx.fillText('series',137,68);const type=index%6;if(type===0)photo(images[0],55,130,970,1160,sceneT);if(type===1){photo(images[0],55,130,650,760,sceneT);photo(images[1]||images[0],740,130,285,500,sceneT,.1);photo(images[2]||images[0],740,665,285,625,sceneT,.2)}if(type===2){photo(images[0],55,130,460,1160,sceneT);photo(images[1]||images[0],550,130,475,550,sceneT,.1);photo(images[2]||images[0],550,715,475,575,sceneT,.2)}if(type===3){images.slice(0,5).forEach((im,i)=>{const p=[[55,130,560,650],[650,130,375,370],[650,535,375,755],[55,815,265,475],[350,815,265,475]][i];photo(im,...p,sceneT,i*.07)})}if(type===4){images.slice(0,4).forEach((im,i)=>photo(im,150+i*70,180+i*145,650,800,sceneT,i*.08,(i-1.5)*.06))}if(type===5){images.slice(0,6).forEach((im,i)=>photo(im,55+(i%2)*505,130+Math.floor(i/2)*385,465,350,sceneT,i*.05))}}
async function preview(){if(!accepted.length)return alert('Select a folder first.');$('#empty').style.display='none';const imgs=await Promise.all(accepted.slice(0,12).map(load));let start=performance.now();function tick(now){const sec=(now-start)/1000,idx=Math.floor(sec/2.5)%3;frame(imgs.slice(idx*4,idx*4+5),sec%2.5,idx);if(sec<9)requestAnimationFrame(tick);else $('#status').textContent='Preview complete';}requestAnimationFrame(tick)}
$('#preview').onclick=preview;
$('#render').onclick=async()=>{if(!accepted.length)return alert('Select a folder first.');const duration=Number($('#duration').value),fps=30,total=duration*fps,groupSize=5,scenes=Math.ceil(accepted.length/groupSize),spf=duration/scenes;const mime=['video/mp4;codecs=avc1.42E01E','video/webm;codecs=vp9','video/webm'].find(MediaRecorder.isTypeSupported);if(!mime)return alert('This browser cannot record the canvas. Use current Chrome or Edge.');$('#empty').style.display='none';$('#render').disabled=true;$('#status').textContent=`Loading ${accepted.length} compressed images...`;const imgs=[];for(let i=0;i<accepted.length;i++){imgs.push(await load(accepted[i]));$('#bar').style.width=`${Math.round((i/accepted.length)*15)}%`;await new Promise(r=>setTimeout(r,0))}const stream=canvas.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:10000000}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const ext=mime.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:mime}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cxo-event-montage-4x5.${ext}`;a.click();$('#status').textContent=`Complete. ${ext.toUpperCase()} downloaded.`;$('#bar').style.width='100%';$('#render').disabled=false};rec.start(1000);const started=performance.now();function draw(now){const elapsed=(now-started)/1000,scene=Math.min(scenes-1,Math.floor(elapsed/spf)),local=(elapsed-scene*spf)/spf;frame(imgs.slice(scene*groupSize,scene*groupSize+groupSize),local,scene);const p=Math.min(1,elapsed/duration);$('#bar').style.width=`${15+p*85}%`;$('#status').textContent=`Rendering ${Math.round(p*100)}%`;if(elapsed<duration)requestAnimationFrame(draw);else rec.stop()}requestAnimationFrame(draw)};