const $=s=>document.querySelector(s);const canvas=$('#canvas'),ctx=canvas.getContext('2d');let files=[],photos=[],logo=null,scenes=[],sceneIndex=0,playing=false,selectedSlot=-1,dragging=false,lastPointer=null;
const natural=(a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}),isCustom=f=>/\(custom\)/i.test(f.name),clean=n=>n.replace(/\s*\(custom\)/i,'').replace(/\.[^.]+$/,'').toLowerCase();
$('#pickFolder').onclick=()=>$('#folder').click();$('#pickLogo').onclick=()=>$('#logoInput').click();$('#folder').onchange=e=>scan([...e.target.files]);$('#logoInput').onchange=e=>loadLogo(e.target.files[0]);$('#build').onclick=buildStoryboard;$('#prev').onclick=()=>selectScene(sceneIndex-1);$('#next').onclick=()=>selectScene(sceneIndex+1);$('#play').onclick=playPreview;$('#shuffle').onclick=shuffleScene;$('#layoutSelect').onchange=e=>{scenes[sceneIndex].layout=e.target.value;drawScene(scenes[sceneIndex],.55);renderCards()};
const imageFromFile=file=>new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({img,url});img.onerror=reject;img.src=url});
async function loadLogo(file){if(!file)return;const x=await imageFromFile(file);logo=x;$('#logoStatus').textContent=file.name;drawCurrent()}
async function scan(input){files=input.filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));$('#folderName').textContent=input[0]?.webkitRelativePath.split('/')[0]||'Folder selected';$('#scanned').textContent=files.length;$('#workspace').hidden=false;$('#status').textContent='Reading image dimensions…';const customs=files.filter(isCustom),bases=new Set(customs.map(f=>clean(f.name))),unmatched=files.filter(f=>!isCustom(f)&&!bases.has(clean(f.name)));const chosen=$('#customOnly').checked?customs:[...customs,...unmatched];photos=[];for(let i=0;i<chosen.length;i++){const x=await imageFromFile(chosen[i]),r=x.img.width/x.img.height,type=r>.112? (r>1.15?'landscape':r<.82?'portrait':'square'):'portrait';photos.push({file:chosen[i],name:chosen[i].name,img:x.img,url:x.url,type,ratio:r,fx:.5,fy:.5,fit:'fill',zoom:1});$('#bar').style.width=`${Math.round((i+1)/chosen.length*100)}%`}$('#accepted').textContent=photos.length;$('#portrait').textContent=photos.filter(p=>p.type==='portrait').length;$('#landscape').textContent=photos.filter(p=>p.type==='landscape').length;$('#warnings').textContent=unmatched.length;$('#status').textContent='Folder ready. Build the smart storyboard.';$('#bar').style.width='0'}
const slots={hero:['landscape'],mixed:['landscape','portrait','portrait'],portraits:['portrait','portrait','portrait'],magazine:['landscape','square','portrait','portrait','square'],duo:['portrait','portrait'],grid:['square','square','square','square','square','square']};
function pick(pool,want){let i=pool.findIndex(p=>p.type===want);if(i<0&&want==='square')i=pool.findIndex(p=>p.type!=='portrait');if(i<0)i=0;return pool.splice(i,1)[0]}
function buildStoryboard(){if(!photos.length)return alert('Select the event image folder first.');let ordered=[...photos];const mode=$('#order').value;if(mode==='filename')ordered.sort((a,b)=>natural(a.file,b.file));else if(mode==='modified')ordered.sort((a,b)=>a.file.lastModified-b.file.lastModified||natural(a.file,b.file));else ordered.sort(()=>Math.random()-.5);const pool=[...ordered],cycle=['mixed','portraits','magazine','duo','grid','hero'];scenes=[];let c=0;while(pool.length){let layout=cycle[c++%cycle.length],needs=slots[layout];if(pool.length<needs.length){layout=pool.length===1?'hero':pool.length===2?'duo':pool.length===3?'mixed':'magazine';needs=slots[layout].slice(0,pool.length)}const items=needs.map(w=>pick(pool,w)).filter(Boolean);scenes.push({layout,items})}sceneIndex=0;renderCards();selectScene(0);$('#render').disabled=false;$('#empty').style.display='none';$('#status').textContent=`${scenes.length} scenes built with orientation-aware matching.`}
function rects(layout){return {hero:[[55,125,970,1165]],mixed:[[55,125,610,1165],[700,125,325,555],[700,715,325,575]],portraits:[[55,125,306,1165],[387,125,306,1165],[719,125,306,1165]],magazine:[[55,125,575,650],[665,125,360,360],[665,520,360,770],[55,810,270,480],[360,810,270,480]],duo:[[55,125,465,1165],[560,125,465,1165]],grid:[[55,125,465,350],[560,125,465,350],[55,500,465,350],[560,500,465,350],[55,875,465,415],[560,875,465,415]]}[layout]}
function bg(t){const g=ctx.createLinearGradient(0,0,1080,1350);g.addColorStop(0,'#132949');g.addColorStop(1,'#071327');ctx.fillStyle=g;ctx.fillRect(0,0,1080,1350);ctx.globalAlpha=.2;ctx.strokeStyle='#31859d';for(let i=0;i<12;i++){ctx.beginPath();ctx.moveTo((i*127+t*120)%1200-100,i*115);ctx.lineTo((i*127+t*120)%1200+280,i*115+65);ctx.stroke()}ctx.globalAlpha=1}
function crop(p,x,y,w,h,t){ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,22);ctx.clip();const scale=p.fit==='fit'?Math.min(w/p.img.width,h/p.img.height):Math.max(w/p.img.width,h/p.img.height)*(1+.045*t)*(p.zoom||1);const nw=p.img.width*scale,nh=p.img.height*scale,dx=x+(w-nw)*p.fx,dy=y+(h-nh)*p.fy;if(p.fit==='fit'){ctx.filter='blur(24px)';const bs=Math.max(w/p.img.width,h/p.img.height)*1.1;ctx.globalAlpha=.55;ctx.drawImage(p.img,x+(w-p.img.width*bs)/2,y+(h-p.img.height*bs)/2,p.img.width*bs,p.img.height*bs);ctx.filter='none';ctx.globalAlpha=1}ctx.drawImage(p.img,dx,dy,nw,nh);ctx.restore()}
function drawLogo(){if(!logo)return;const w=Number($('#logoSize').value),h=w/logo.img.width*logo.img.height,pos=$('#logoPosition').value,m=50;let x=m,y=m;if(pos==='tc')x=(1080-w)/2;if(pos==='tr')x=1080-w-m;if(pos==='bl'){x=m;y=1350-h-m}if(pos==='br'){x=1080-w-m;y=1350-h-m}ctx.drawImage(logo.img,x,y,w,h)}
function drawScene(scene,t=0){if(!scene)return;bg(t);const rs=rects(scene.layout);scene.items.forEach((p,i)=>{if(rs[i]){crop(p,...rs[i],t);if(i===selectedSlot&&!playing){ctx.save();ctx.strokeStyle='#70c6dc';ctx.lineWidth=8;ctx.beginPath();ctx.roundRect(...rs[i],22);ctx.stroke();ctx.restore()}}});drawLogo()}
function drawCurrent(){if(scenes.length)drawScene(scenes[sceneIndex],.5)}
function renderCards(){const box=$('#sceneCards');box.innerHTML='';scenes.forEach((s,i)=>{const b=document.createElement('button');b.className='sceneCard '+(i===sceneIndex?'active':'');b.innerHTML=`<b>Scene ${i+1}</b><span>${s.layout} · ${s.items.length} photos</span>`;b.onclick=()=>selectScene(i);box.append(b)})}
function selectScene(i){if(!scenes.length)return;sceneIndex=(i+scenes.length)%scenes.length;selectedSlot=-1;updateCanvasTools();drawCurrent();renderCards();renderEditor();$('#sceneLabel').textContent=`Scene ${sceneIndex+1} of ${scenes.length}`}
function renderEditor(){const scene=scenes[sceneIndex];$('#sceneEditor').hidden=false;$('#editingTitle').textContent=`Editing scene ${sceneIndex+1}`;$('#layoutSelect').value=scene.layout;const box=$('#slotEditor');box.innerHTML='';scene.items.forEach((p,i)=>{const d=document.createElement('div');d.className='slot';d.innerHTML=`<img src="${p.url}"><label>Photo<select class="swap"></select></label><label>Crop<select class="fit"><option value="fill">Fill frame</option><option value="fit">Show full photo + blur</option></select></label><label>Horizontal focal point<input class="fx" type="range" min="0" max="1" step=".05" value="${p.fx}"></label><label>Vertical focal point<input class="fy" type="range" min="0" max="1" step=".05" value="${p.fy}"></label>`;const sel=d.querySelector('.swap');photos.forEach((q,j)=>{const o=document.createElement('option');o.value=j;o.textContent=q.name;o.selected=q===p;sel.append(o)});sel.onchange=e=>{scene.items[i]=photos[Number(e.target.value)];renderEditor();drawCurrent()};const fit=d.querySelector('.fit');fit.value=p.fit;fit.onchange=e=>{p.fit=e.target.value;drawCurrent()};d.querySelector('.fx').oninput=e=>{p.fx=Number(e.target.value);drawCurrent()};d.querySelector('.fy').oninput=e=>{p.fy=Number(e.target.value);drawCurrent()};box.append(d)})}
function shuffleScene(){if(!scenes.length)return;const used=new Set(scenes[sceneIndex].items),available=photos.filter(p=>!used.has(p));scenes[sceneIndex].items=scenes[sceneIndex].items.map((p,i)=>{const matches=available.filter(q=>q.type===p.type);return (matches.length?matches:available).splice(Math.floor(Math.random()*Math.max(1,(matches.length?matches:available).length)),1)[0]||p});selectScene(sceneIndex)}
function playPreview(){if(playing||!scenes.length)return;playing=true;let start=performance.now(),len=Math.min(8,scenes.length),per=2.2;function tick(now){const sec=(now-start)/1000,idx=Math.min(len-1,Math.floor(sec/per));drawScene(scenes[idx],(sec%per)/per);$('#sceneLabel').textContent=`Preview scene ${idx+1} of ${len}`;if(sec<len*per)requestAnimationFrame(tick);else{playing=false;selectScene(sceneIndex)}}requestAnimationFrame(tick)}

function slotAtPoint(clientX,clientY){if(!scenes.length)return -1;const r=canvas.getBoundingClientRect(),x=(clientX-r.left)*canvas.width/r.width,y=(clientY-r.top)*canvas.height/r.height,rs=rects(scenes[sceneIndex].layout);return rs.findIndex(a=>x>=a[0]&&x<=a[0]+a[2]&&y>=a[1]&&y<=a[1]+a[3])}
function updateCanvasTools(){const ok=selectedSlot>=0&&scenes[sceneIndex]?.items[selectedSlot];['swapLeft','swapRight','replaceImage','toggleFit','removeImage'].forEach(id=>$('#'+id).disabled=!ok);$('.canvasWrap').classList.toggle('editing',ok)}
canvas.addEventListener('pointerdown',e=>{const i=slotAtPoint(e.clientX,e.clientY);if(i<0||!scenes[sceneIndex]?.items[i]){selectedSlot=-1;updateCanvasTools();drawCurrent();return}selectedSlot=i;dragging=true;lastPointer={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);$('.canvasWrap').classList.add('dragging');updateCanvasTools();drawCurrent()});
canvas.addEventListener('pointermove',e=>{if(!dragging||selectedSlot<0)return;const p=scenes[sceneIndex].items[selectedSlot],r=canvas.getBoundingClientRect(),dx=(e.clientX-lastPointer.x)/r.width,dy=(e.clientY-lastPointer.y)/r.height;p.fx=Math.max(0,Math.min(1,p.fx-dx*1.8));p.fy=Math.max(0,Math.min(1,p.fy-dy*1.8));lastPointer={x:e.clientX,y:e.clientY};drawCurrent()});
canvas.addEventListener('pointerup',e=>{dragging=false;lastPointer=null;$('.canvasWrap').classList.remove('dragging');renderEditor()});
canvas.addEventListener('wheel',e=>{if(selectedSlot<0)return;e.preventDefault();const p=scenes[sceneIndex].items[selectedSlot];p.zoom=Math.max(.85,Math.min(1.65,(p.zoom||1)+(e.deltaY<0?.05:-.05)));drawCurrent()},{passive:false});
function swapSlot(direction){const scene=scenes[sceneIndex],j=selectedSlot+direction;if(j<0||j>=scene.items.length)return;[scene.items[selectedSlot],scene.items[j]]=[scene.items[j],scene.items[selectedSlot]];selectedSlot=j;drawCurrent();renderEditor()}
$('#swapLeft').onclick=()=>swapSlot(-1);$('#swapRight').onclick=()=>swapSlot(1);
$('#toggleFit').onclick=()=>{const p=scenes[sceneIndex].items[selectedSlot];p.fit=p.fit==='fill'?'fit':'fill';drawCurrent();renderEditor()};
$('#removeImage').onclick=()=>{if(selectedSlot<0)return;scenes[sceneIndex].items.splice(selectedSlot,1);selectedSlot=-1;updateCanvasTools();drawCurrent();renderEditor();renderCards()};
$('#replaceImage').onclick=()=>{if(selectedSlot<0)return;const sel=$('#quickPhotoSelect');sel.innerHTML='';photos.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;sel.append(o)});$('#quickReplace').hidden=false};
$('#applyReplace').onclick=()=>{if(selectedSlot<0)return;scenes[sceneIndex].items[selectedSlot]=photos[Number($('#quickPhotoSelect').value)];$('#quickReplace').hidden=true;drawCurrent();renderEditor()};$('#cancelReplace').onclick=()=>$('#quickReplace').hidden=true;
updateCanvasTools();
$('#logoPosition').onchange=drawCurrent;$('#logoSize').oninput=drawCurrent;
$('#render').onclick=()=>renderVideo();async function renderVideo(){if(!scenes.length)return;const duration=Number($('#duration').value),fps=30,per=duration/scenes.length,mime=['video/mp4;codecs=avc1.42E01E','video/webm;codecs=vp9','video/webm'].find(MediaRecorder.isTypeSupported);if(!mime)return alert('Use current Edge or Chrome.');const stream=canvas.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:10000000}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{const ext=mime.includes('mp4')?'mp4':'webm',blob=new Blob(chunks,{type:mime}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`cxo-smart-montage-1080x1350.${ext}`;a.click();$('#status').textContent=`Complete. ${ext.toUpperCase()} downloaded.`;$('#render').disabled=false};$('#render').disabled=true;rec.start(1000);const st=performance.now();function tick(now){const sec=(now-st)/1000,idx=Math.min(scenes.length-1,Math.floor(sec/per)),local=(sec-idx*per)/per;drawScene(scenes[idx],local);const p=Math.min(1,sec/duration);$('#bar').style.width=`${p*100}%`;$('#status').textContent=`Rendering ${Math.round(p*100)}%`;if(sec<duration)requestAnimationFrame(tick);else rec.stop()}requestAnimationFrame(tick)}