import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig, random} from 'remotion';
import {loadFont} from '@remotion/google-fonts/Barlow';
const {fontFamily}=loadFont();

type Props={images:string[]; music?:string; eventTitle:string; eventDate:string; closingMessage:string; secondsPerScene:number};
export const defaultProps:Props={images:['images/01.jpg','images/02.jpg','images/03.jpg','images/04.jpg','images/05.jpg','images/06.jpg'],music:'',eventTitle:"Member Appreciation Dinner '26",eventDate:'17 September 2026',closingMessage:'Thank you for joining us',secondsPerScene:2.4};
export const calculateMetadata=({props}:any)=>{const scenes=Math.max(1,Math.ceil(props.images.length/5));return {durationInFrames:Math.max(300,90+scenes*Math.round(props.secondsPerScene*30)+120)};};
const navy='#0b1732', slate='#132949', teal='#31859d';
const fit=(src:string)=>src.startsWith('http')?src:staticFile(src);

const Lines:React.FC<{seed:number}>=({seed})=>{const f=useCurrentFrame();return <AbsoluteFill style={{overflow:'hidden',opacity:.38}}>{Array.from({length:14}).map((_,i)=>{const y=(i*103+seed*37)%1350;const x=((f*(0.5+i%3*.25)+i*97+seed*83)%1300)-130;return <div key={i} style={{position:'absolute',left:x,top:y,width:180+i%4*75,height:1,background:i%3===0?teal:'#fff',transform:`rotate(${i%2?18:-18}deg)`,boxShadow:`0 0 16px ${teal}`}}/>})}</AbsoluteFill>};
const Brand:React.FC=()=> <div style={{position:'absolute',top:55,left:64,right:64,display:'flex',alignItems:'center',justifyContent:'space-between',zIndex:20}}><div style={{fontWeight:700,fontSize:38,letterSpacing:-1}}>CXO <span style={{fontWeight:300}}>series</span></div><div style={{width:160,height:2,background:teal}}/></div>;
const Intro:React.FC<Props>=({eventTitle,eventDate})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f,fps,config:{damping:14}});return <AbsoluteFill style={{background:`radial-gradient(circle at 70% 35%,${teal}44,transparent 36%),linear-gradient(145deg,${slate},${navy})`,fontFamily,color:'white'}}><Lines seed={1}/><Brand/><div style={{position:'absolute',left:70,right:70,top:330,transform:`translateY(${(1-p)*70}px)`,opacity:p}}><div style={{fontSize:116,fontWeight:200,lineHeight:.95}}>An evening<br/>to remember.</div><div style={{marginTop:44,fontSize:35,color:'#9ed9e8',fontWeight:500}}>{eventTitle}</div><div style={{marginTop:12,fontSize:25,letterSpacing:3,textTransform:'uppercase'}}>{eventDate}</div></div><div style={{position:'absolute',bottom:110,left:70,fontSize:21,letterSpacing:5,color:'#ffffffaa'}}>BRINGING TECHNOLOGY LEADERS TOGETHER</div></AbsoluteFill>};

const layouts=['hero','duo','trio','magazine','stack'] as const;
const Photo:React.FC<{src:string;style?:React.CSSProperties;delay?:number}>=({src,style,delay=0})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f-delay,fps,config:{damping:16,mass:.7}});return <div style={{overflow:'hidden',borderRadius:22,background:'#091426',boxShadow:'0 22px 60px #0008',...style,transform:`${style?.transform||''} scale(${.88+.12*p})`,opacity:p}}><Img src={fit(src)} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${1.12-.06*p})`}}/></div>};
const Gallery:React.FC<{items:string[];index:number}>=({items,index})=>{const layout=layouts[index%layouts.length];const base:React.CSSProperties={position:'absolute'};return <AbsoluteFill style={{background:`linear-gradient(145deg,${navy},${slate})`,fontFamily,color:'white',padding:60}}><Lines seed={index+3}/><Brand/><div style={{position:'absolute',left:60,right:60,top:145,bottom:70}}>
{layout==='hero'&&<><Photo src={items[0]} style={{...base,inset:0}}/><div style={{position:'absolute',bottom:55,left:55,fontSize:56,fontWeight:300,textShadow:'0 3px 24px #000'}}>The moments that connected us.</div></>}
{layout==='duo'&&<>{items.slice(0,2).map((s,i)=><Photo key={s+i} src={s} delay={i*5} style={{...base,top:i?520:0,left:i?190:0,right:i?0:190,height:610}}/>)}</>}
{layout==='trio'&&<><Photo src={items[0]} style={{...base,left:0,top:0,width:610,height:1080}}/><Photo src={items[1]||items[0]} delay={5} style={{...base,right:0,top:0,width:330,height:510}}/><Photo src={items[2]||items[0]} delay={10} style={{...base,right:0,bottom:0,width:330,height:510}}/></>}
{layout==='magazine'&&<>{items.slice(0,5).map((s,i)=>{const pos=[{left:0,top:0,width:570,height:650},{right:0,top:0,width:350,height:360},{right:0,top:400,width:350,height:650},{left:0,bottom:0,width:270,height:390},{left:300,bottom:0,width:270,height:390}][i];return <Photo key={s+i} src={s} delay={i*4} style={{...base,...pos}}/>})}</>}
{layout==='stack'&&<>{items.slice(0,4).map((s,i)=><Photo key={s+i} src={s} delay={i*5} style={{...base,left:100+i*70,top:90+i*105,width:650,height:780,transform:`rotate(${(i-1.5)*4}deg)`}}/>)}</>}
</div></AbsoluteFill>};
const Outro:React.FC<Props>=({closingMessage,eventDate})=>{const f=useCurrentFrame();const a=interpolate(f,[0,30],[0,1],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:`radial-gradient(circle at 50% 70%,${teal}55,transparent 40%),${navy}`,fontFamily,color:'white',display:'flex',justifyContent:'center',alignItems:'center',textAlign:'center',opacity:a}}><Lines seed={99}/><Brand/><div><div style={{fontSize:104,fontWeight:200}}>{closingMessage}</div><div style={{marginTop:30,fontSize:34,color:'#9ed9e8'}}>CxO Series</div><div style={{marginTop:12,fontSize:22,letterSpacing:4}}>{eventDate}</div></div></AbsoluteFill>};
export const CxoEventVideo:React.FC<Props>=(props)=>{const sceneFrames=Math.round(props.secondsPerScene*30);const groups:Array<string[]>=[];for(let i=0;i<props.images.length;i+=5)groups.push(props.images.slice(i,i+5));const outroStart=90+groups.length*sceneFrames;return <AbsoluteFill style={{background:navy}}><Sequence durationInFrames={90}><Intro {...props}/></Sequence>{groups.map((g,i)=><Sequence key={i} from={90+i*sceneFrames} durationInFrames={sceneFrames}><Gallery items={g} index={i}/></Sequence>)}<Sequence from={outroStart} durationInFrames={120}><Outro {...props}/></Sequence>{props.music?<Audio src={fit(props.music)} volume={0.72}/>:null}</AbsoluteFill>};
